### PR TITLE
customised the cursor

### PR DESCRIPTION
**Pull request by Mehul-12**

### CODE REVIEW

**Comment by Mehul-12** [comment]
https://mehul-12.github.io/Geektoberfest-Main/

**Comment by tsukii21** [comment]
Your link is giving 404 error

**Comment by Mehul-12** [comment]
yeah, these live links activate after a few minutes

**Comment by tsukii21** [comment]
Okay, and for the participants section issue, after running your site, check the console and report it here, each request has error handling, so we will get the issue

**Pull request closed without merging**
