### PR TITLE
Added the custom scrollbar and custom cursor

### LINKED ISSUE #84: Custom cursor and scrollbar
The default cursor and the scrollbar are getting in the way of the overall theme. They need to be customized.
(the cursor doesn't need to be flashy or animated, a simple dot which is visible anywhere in the page would do)

### PR DESCRIPTION
**Pull request by sandy9808**
Fixes #84 
It is live at https://sandy9808.github.io/Geektoberfest-Main/
If any color has to be changed then please do tell.
The custom scrollbar and cursor is supported in mozilla as well.

### CODE REVIEW

**Comment by tsukii21** [comment]
The cursor is looking cool. Can you make it lighter though. The best option will be to add a blending mode I think (difference) using backdrop filter

**Comment by tsukii21** [comment]
And on link and button hovers, the CSS cursor:pointer is overriding your custom cursor. Fix this

**Comment by tsukii21** [comment]
And for the scrollbar, either the bar or the thumb has a white border. Remove it and make the gray thumb rounded

**Comment by sandy9808** [comment]
> And for the scrollbar, either the bar or the thumb has a white border. Remove it and make the gray thumb rounded

But this can be done only in chrome and edge, not in mozilla. Hence chrome and mozilla will have different scrollbar design. is it fine ?

**Comment by sandy9808** [comment]
There is one problem with the custom cursor in mobile, wherever we are touching the cursor is just following the touch and it is not looking good, so should i disable custom cursor for the touch devices ?

**Comment by tsukii21** [comment]
Yea disable the cursors for medium and small devices and the issue with mozilla, dont worry about it. Just make it work for chrome

**Comment by tsukii21** [comment]
And...the color of the cursor is still the same. Did you do sth about it?

**Comment by sandy9808** [comment]
> And...the color of the cursor is still the same. Did you do sth about it?

I changed the color from #0000ff to #1919ff, ok i will make it more lighter then.

**Comment by tsukii21** [comment]
Yea it looks good. Further improvements will be on a new issue but for now its all right. Good work

**Pull request merged**
