### PR TITLE
added preloader

### PR DESCRIPTION
**Pull request by kumarmanish03**
#55 

Live link: https://confident-bassi-8f9293.netlify.app/

### CODE REVIEW

**Comment by sggts04** [comment]
Can you make the the background of the loader match the general colour of the homepage?
Currently it looks weird that a white loader transitions into a dark blue page.

**Comment by sggts04** [comment]
Why is there a flashbang between the loader ending and the site being visible? Its almost blinding .

**Comment by kumarmanish03** [comment]
see if this fine

**Comment by sggts04** [comment]
Almost done. 
1. The background color can be a little bit lighter, too hard on the eyes right now.
2. Squash your commits.

**Comment by kumarmanish03** [comment]
Hey, I have some trouble in squashing commits, as i have made some commits directly from github and some from local repo ;), also i deleted old forked repo in between (due to some trouble)
If possible kindly merge if all fine

**Comment by sggts04** [comment]
I may have agreed to do it earlier, but now you're trying to merge 10 COMMITS, which is definitely a no no. If you have problems squashing then you can delete your fork and re-fork and just paste the new code again.

**Pull request closed without merging**
