### PR TITLE
Redesign Profile Page to include more stats with better design

### LINKED ISSUE #212: Redesign profile page.
Each person's profile page is now available.

Example URL: `https://geekhaven.github.io/Geektoberfest-Main/profile.html?username=2802harsh`. You can change `2802harsh` to your own username to get your own profile.

You have to redesign this profile page to look better(Make sure to check pages of different profiles to verify your styling is consistent):

1. Improve the header. Better font, also fix the grammer, coloring.
2. Show the number of PRs made.
3. Show the PRs in a styled table instead of a list, and make sure they are hyperlinked(they cannot be clicked as of now)
4. Improve the overall font and sizes etc, make it look good.
5. Make the social icons a little bigger and better placed.

### PR DESCRIPTION
**Pull request by 2802harsh**
# Pull Request
## Changes Made
- Redesigned the Profile Page
   - Better Design
   - Responsive
   - Includes Navbar and Footer ( same as homepage)
   - Dark Mode also handled

- PRs list changed to table
- It now contains the 
   - PR Link
   - Issue Link
   - PR Summary( the title of PR + changes made : additions and deletions )

## Screenshots
- Screenshot from 2020-10-21 16-27-01
- Screenshot from 2020-10-21 16-27-15
### Dark Mode
- Screenshot from 2020-10-21 16-27-28
- Screenshot from 2020-10-21 16-27-37
### Mobile View
Screenshot from 2020-10-21 18-23-08
Screenshot from 2020-10-21 18-23-17
Screenshot from 2020-10-21 18-23-39
Screenshot from 2020-10-21 18-23-48

### CODE REVIEW

**Comment by sggts04** [comment]
Can you provide a live link?
Also, try to squash these 15 commits into 1-2 commits.

**Comment by sggts04** [comment]
Great work btw! Love the design and functionality.

**Comment by 2802harsh** [comment]
I have added the Live Link @sggts04

**Comment by 2802harsh** [comment]
> Great work btw! Love the design and functionality.

Thanks

**Comment by sggts04** [comment]
Okay, looks great, just squash your commits and I will merge.

**Comment by 2802harsh** [comment]
> Okay, looks great, just squash your commits and I will merge.

Alright

**Pull request closed without merging**
