### PR TITLE
Fixed the title of the Profile Page issue

### PR DESCRIPTION
**Pull request by geeks5551**
#214 

screenshot
Screenshot (3124)

### CODE REVIEW

**Comment by geeks5551** [comment]
@sggts04 pls review

**Comment by sggts04** [comment]
Live link? You have so many tabs open, the title of the page is not even visible, what was the point of the screenshot?

**Comment by sggts04** [comment]
1. The title should be 'Profile - Shivam Agrahari' not just 'Shivam Agrahari'
2. Share a live link

**Comment by sggts04** [comment]
@geeks5551 look at the changes I asked ^

**Comment by geeks5551** [comment]
ok i am changing the needful

**Comment by geeks5551** [comment]
As there is some merge conflicts so I am closing this or and sending new one

**Pull request closed without merging**
