### PR TITLE
Add navbar and footer to leaderboard page

### LINKED ISSUE #271: Add navbar and footer to Leaderboard
Add the same navbar and footer as the main page and the profile page to the leaderboard page. Make sure all the functionalities are working.

### PR DESCRIPTION
**Pull request by thelavenderhue**
Fixes #271

### CODE REVIEW

**Comment by sggts04** [comment]
Live link?

**Comment by thelavenderhue** [comment]
https://thelavenderhue.github.io/

**Comment by sggts04** [comment]
Nothing happens on clicking the hamburger in mobile view

**Comment by thelavenderhue** [comment]
Fixing it now

**Comment by thelavenderhue** [comment]
Updated
https://thelavenderhue.github.io/leaderboard.html

**Pull request merged**
