### PR TITLE
Fixed countdown spacing

### PR DESCRIPTION
**Pull request by aj0311**
https://aj0311.github.io/Geektoberfest-Main/
Screenshot (33)

### CODE REVIEW

**Comment by tsukii21** [comment]
You are supposed to lessen the space between the numbers and the labels. There should be some bottom padding(same as top)

**Comment by aj0311** [comment]
@tsukii21 Sorry can you please explain a bit more... that where am I supposed to put some padding.

**Comment by tsukii21** [comment]
There should be some space between the line with labels (hour, minutes etc) and the bottom of the timer div (same as there is space between "Event Ends in" and top. Add a uniform padding in the timer div

**Comment by tsukii21** [comment]
And again your main task is to make the label line closer to the actual numbers. Currently there is too much space between them

**Comment by tsukii21** [comment]
Yeah, it looks better. good job

**Comment by tsukii21** [comment]
Now just squash your commits to a singe one to avoid any mess and it will be merged

**Comment by aj0311** [comment]
Heyy! I was working on the main branch and I had performed git pull to get the changes from the main repo. Now my log history consists of the commits that are not mine and if I squash them then the squashed commit would contain the changes of others as well. If there is a way to solve this then please help.

**Comment by tsukii21** [comment]
Okay, since your commits are not that many, I am merging your PR

**Pull request merged**
