### PR TITLE
Fixed countdown #127

### PR DESCRIPTION
**Pull request by aj0311**

### CODE REVIEW

**Comment by sggts04** [comment]
Live link and screenshot?

**Comment by aj0311** [comment]
@sggts04 while resolving conflicts I missed my changes of index.html and I just figured it out. I'll make the corrections and send a pr in some time. Sorry for the inconvenience.

**Comment by tsukii21** [comment]
We still need a live link to see changes @aj0311

**Comment by aj0311** [comment]
I have sent a new pr so I am closing this pr.

**Pull request closed without merging**
