### PR TITLE
Added More Contributions From geeks5551 into geeks.json

### PR DESCRIPTION
**Pull request by geeks5551**

### CODE REVIEW

**Comment by sggts04** [comment]
Go through all the PR links you have mentioned, most of them are issue links instead of PR links, please rectify.

**Comment by geeks5551** [comment]
I have done the required rectification @sggts04

**Comment by sggts04** [comment]
Check all the links again bro, the elevate lab ones are still linking to issues and not PRs. Recheck all your links.

**Comment by geeks5551** [comment]
now i think it is fine @sggts04

**Comment by sggts04** [comment]
https://github.com/GeekHaven/Geektoberfest-Main/pull/214
https://github.com/GeekHaven/Geektoberfest-Main/pull/198

Are these PRs or issues? Come on dude, just open all your links and check.

**Comment by sggts04** [comment]
#128
#77
also, bro check all your links, how many times do I have to say this.

**Comment by sggts04** [comment]
Hey! You completed your 6 PRs to Geekhaven repos! Congrats!

If you want to do more PRs and contribute more to Open Source, then you are free to go and contribute to other public repos on Github, you can keep adding them to this file, however, we have set a 6 PR limit to Geekhaven repos so that newer people can be assigned more issues and get to solve the beginner friendly parts.

**Pull request merged**
