### PR TITLE
Added Saarani-Frontend to the Projects list, issue #285

### PR DESCRIPTION
**Pull request by Aditya-2001**

### CODE REVIEW

**Comment by sggts04** [comment]
Live link?

**Comment by Aditya-2001** [comment]
@sggts04 how to create it?

**Comment by sggts04** [comment]
Scroll down to Github Pages in your repo settings and choose banch master.

**Comment by Aditya-2001** [comment]
https://aditya-2001.github.io/Geektoberfest-Main/

**Pull request merged**
