### PR TITLE
Added  a preloader gif to pr table

### LINKED ISSUE #265: Add a preloader gif to the PR table in the profile page when the PRs are getting fetched.
In the profile page, the table with the details of PRs takes some time to load, add a preloader gif for that table. Make sure the gif you choose matches the vibe of the page.

Don't add a preloader to the whole profile.html page, but only for the PR table while its loading.

### PR DESCRIPTION
**Pull request by shahidsiddiqui786**
fixes #265

### CODE REVIEW

**Comment by sggts04** [comment]
Live link?

**Comment by shahidsiddiqui786** [comment]
> 
> 
> Live link?

hey @sggts04 
live link
 https://shahidsiddiqui786.github.io/Geektoberfest-Main/

**Comment by sggts04** [comment]
I am not able to see any loading gif on https://geekhaven.github.io/Geektoberfest-Main/profile.html?username=Priyansh-09 when the table is loading?

**Comment by shahidsiddiqui786** [comment]
> I am not able to see any loading gif on https://geekhaven.github.io/Geektoberfest-Main/profile.html?username=Priyansh-09 when the table is loading?

Hey @sggts04 
You are viewing geekhaven repository page, although you have not merge the pr yet.
You need to see the live page hosted by my fork repo to see the changes 

https://shahidsiddiqui786.github.io/Geektoberfest-Main/profile.html?username=Priyansh-09

**Comment by sggts04** [comment]
My mistake, I went on your URL and then clicked on a profile from there which redirected me to the Geekhaven page without me realizing.

Okay I can see the preloader, works fine, but I don't like the gif at all, can you use some different preloader gif? Something that matches the vibe of the page?

**Comment by shahidsiddiqui786** [comment]
> 
> 
> My mistake, I went on your URL and then clicked on a profile from there which redirected me to the Geekhaven page without me realizing.
> 
> Okay I can see the preloader, works fine, but I don't like the gif at all, can you use some different preloader gif? Something that matches the vibe of the page?

oh! you don't like the gif
ok I have selected some gif ,reply me which one is better

0 4mEOputjtEJjsemg
dribble-guy-cloud-800x600
bouncing

**Comment by sggts04** [comment]
The ping pong one seems fine.

**Comment by sggts04** [comment]
You need to scale down the gif. Its appearing very huge, it gets cutoff by other elements, and looks very pixelated.

**Comment by shahidsiddiqui786** [comment]
@sggts04 
Done

**Comment by sggts04** [comment]
I dont see any loading gif on https://shahidsiddiqui786.github.io/Geektoberfest-Main/profile.html?username=Priyansh-09

**Comment by sggts04** [comment]
and why have you done this
image

**Comment by shahidsiddiqui786** [comment]
> 
> 
> and why have you done this
> image

sorry
actually i have to change it in different branch
By mistake I changed it in the main branch
I am reverting soon

**Comment by shahidsiddiqui786** [comment]
> 
> 
> I dont see any loading gif on https://shahidsiddiqui786.github.io/Geektoberfest-Main/profile.html?username=Priyansh-09

please see live changes here
https://livegectoberfestmain.netlify.app/profile.html?username=Priyansh-09
I think, I have fixed everything else

**Pull request merged**
