### PR TITLE
Fixed Mobile Navbar HamburgerBackgroundColor Issue

### PR DESCRIPTION
**Pull request by geeks5551**
#198 

Screenshots

ham1
ham2

### CODE REVIEW

**Comment by geeks5551** [comment]
Actually there are some issues while generating live link so pls review by the screenshots attached @sggts04

**Comment by sggts04** [comment]
The live link is necessary here bro. I can't judge from screenshots.

**Comment by geeks5551** [comment]
https://geeks5551.github.io/Geektoberfest-Main/

**Comment by geeks5551** [comment]
i have generated the live link pls review @sggts04

**Comment by sggts04** [comment]
The background only shows up in exactly the mobile view, but the issue was about hamburger.

image

At a little bigger width (usually a Tab's screen size), the hamburger is there but background isn't. You need to make sure you add that background for whenever that hamburger is there, not just for the mobile.

**Comment by geeks5551** [comment]
@sggts04 pls review  i have made required changes 
live link:-https://geeks5551.github.io/Geektoberfest-Main/

**Pull request merged**
