### PR TITLE
Added some text about the Discord Server also a link to it in the about section

### PR DESCRIPTION
**Pull request by shyamTayal**
For issue #108 , Also please tell if it is okay for night mode, also
here is live preview : https://shyamTayal.github.io/Geektoberfest-Main/

### CODE REVIEW

**Comment by sggts04** [comment]
image

In Dark Mode, it is not visible that 'Discord Server' is a hyperlink, it should be a different colour

**Comment by shyamTayal** [comment]
Should i make it of the one color for both dark and light mode or just a different color for dark mode

**Comment by sggts04** [comment]
Just different colour for dark mode, the colours in light mode are fine.

**Comment by shyamTayal** [comment]
you may check now, with the above link

**Comment by sggts04** [comment]
Looks good!

**Pull request merged**
