### PR TITLE
Fixes issue #4 Converted navbar into hamburger menu for mobile view

### LINKED ISSUE #4: Convert the navbar into a hamburger menu for mobile view
You can use Bootstrap/Jquery.

### PR DESCRIPTION
**Pull request by AlacritousCreature**
issue #4 

Added hamburger for navbar elements to view on mobile. Please have a look on it........if it is ok or not, or what changes should be done?

[link](https://alacritouscreature.github.io/Geektoberfest-Main/)

### CODE REVIEW

**Comment by sggts04** [comment]
On my phone the hamburger is coming in the left in a new line. Shouldn't it be in the extreme right? In the same line as the Title?

**Comment by AlacritousCreature** [comment]
oh yes....i'll fix it.

**Comment by AlacritousCreature** [comment]
hey @sggts04 ! I have made the hamburger on right in mobile view. Please see if some changes are to be made.
WhatsApp Image 2020-10-11 at 10 29 40 PM

**Comment by sggts04** [comment]
Looks good, but there are merge conflicts. 

Resolve the conflicts and the squash all the commits into 1.

**Comment by AlacritousCreature** [comment]
Hey, sorry I am asking that may be silly one.....but I am not getting how to deal with this
I removed the merge conflicts and then I tried to rebase it using "git rebase -i HEAD~6" for last 6 commits
and "git rebase --continue" and I am getting this note, which am unable to understand what to do further.
Please guide through!

Screenshot (229)

**Comment by sggts04** [comment]
Well it says Conflict in xx file so you're gonna have to open those files and fix the conflicts, just like you would fix conflicts on Github.

If still you're getting problems, maybe other than Rebase, what you could also do is do a soft reset for the previous few commits and then just make a new commit.

**Comment by AlacritousCreature** [comment]
Hey.... after revolving all conflicts it again shows some errors....well this is taking a lot of patience and time😅...as all conflicts are removed through last commit couldn't it be merged? ....or if not will it be ok if I'll close this pr and delete the repo from my github repos ,and once again fork and make all those things in one commit?

**Comment by sggts04** [comment]
Go ahead if you want to follow the delete and fork route. Its just unethical to have 6 commits pushed for a single small feature.

**Comment by AlacritousCreature** [comment]
okay.

**Pull request closed without merging**
