### PR TITLE
customised the cursor

### PR DESCRIPTION
**Pull request by Mehul-12**
modified the color combination of cursor to look better.
also color of cursor would be changed upon hovering

### CODE REVIEW

**Comment by Mehul-12** [comment]
Live link-https://mehul-12.github.io/Geektoberfest-Main/

**Comment by tsukii21** [comment]
Use a blending mode, and pull the latest changes so you are in sync with the main repo

**Comment by Mehul-12** [comment]
can u pl elaborate and tell the color combination that i should use.

**Comment by tsukii21** [comment]
use this CSS
background-blend-mode: difference;

**Comment by Mehul-12** [comment]
ohk, will apply this

**Comment by tsukii21** [comment]
don't apply it to both, only the outer one, the inner one can remain blue I guess

**Pull request closed without merging**
