### PR TITLE
Remove 'Issue Link' Column from the PRs table in Profile Page

### PR DESCRIPTION
**Pull request by kumaraditya2002**
screencapture-127-0-0-1-5500-Geektoberfest-Main-profile-html-2020-10-22-13_03_43

### CODE REVIEW

**Comment by sggts04** [comment]
Can you share a live link? To make sure it hasn't made any styling problems?

**Comment by kumaraditya2002** [comment]
actually i had made the changes but when i visit the profile section from my repo live link the url is changes to the main repo link and the changes were not reflected so i think you need to merge my pr first to see the the changes

**Comment by sggts04** [comment]
@kumaraditya2002 whats the point of seeing the changes then if I merge the PR first? The whole point is that I need to verify the changes made if they are proper and don't break the site before merging.

Also, what you are doing is making the changes, sending the PR, and then deleting your forked repository, why are you doing that? What's the hurry? Just wait for the merge and then delete your fork. Deleting your fork stops your live link from working, since it was hosted from your fork.

Also, when trying to open the profile section in your site, don't click on someone's profile button, that maybe the problem. Directly navigate to the profile.html?username=xyz page with your url, where xyz is a username

**Comment by kumaraditya2002** [comment]
Now I understood your point😅.
https://kumaraditya2002.github.io/Geektoberfest-Main/profile.html?username=kumaraditya2002

**Pull request merged**
