### PR TITLE
successful in open different sections of the main page directly

### PR DESCRIPTION
**Pull request by Parasagrawal**

### CODE REVIEW

**Comment by Parasagrawal** [comment]
any ubdate??

**Comment by sggts04** [comment]
Live Link?

**Comment by Parasagrawal** [comment]
what do you mean by live link??

**Comment by sggts04** [comment]
Create a Github Pages live link by going into settings. You can check on google/youtube how to do that.

It will give me a live URL to actually check the changes you made.

**Comment by Parasagrawal** [comment]
https://parasagrawal.github.io/geektobermain/

**Pull request merged**
