### PR TITLE
added project cards

### LINKED ISSUE #37: Add all the projects
In the projects section, add all the projects involved in Geektoberfest as cards. Add Relevant image for each repo, Project Title, Description, Maintainer Names and then a repo link button.

**All the projects marked with 'hacktoberfest' tag in the GeekHaven org are part of Geektoberfest.**

**You can make use of Bootstrap cards, just make sure the Cards look good, the current card template present there is not to be used, it doesn't look that good.**

### PR DESCRIPTION
**Pull request by Capt-Titanium**
Fixes #37 
Added cards for all projects under geektoberfest.
Currently, not all projects have a logo so instead I added the icon for the tech stack used for that project.

### CODE REVIEW

**Comment by sggts04** [comment]
Can you squash this into a single commit? Also provide a live link so we can actually view what you have made..

**Comment by Capt-Titanium** [comment]
@sggts04 can you guide me on how to squash this into one commit and to generate a live link for the site?

for your reference I have a [screen recording](https://drive.google.com/file/d/1eQjv0bOW9hxnqJT2Rc-khauY7ApeXaMA/view?usp=sharing) which you can see

**Comment by sggts04** [comment]
You can google about the squashing part its readily available. You can use git rebase or git reset --soft, stackoverflow should help you in that.

For live link, go into your repo settings and scroll to Github Pages, there you can host your master branch and a live link will be generated.

**Comment by Capt-Titanium** [comment]
Heyy @sggts04 ! tbh squashing the commits is entirely new stuff for me so I just followed whatever instructions I found on stackoverflow. 

Here is the [live link](https://capt-titanium.github.io/) for the site.

**Comment by sggts04** [comment]
Okay the live link looks good, great work!
However the squashing hasn't really happened.. Now instead of 2 you are actually pushing 5 commits to the repo..
Also you added an extra config file for the jekyll theme, that is unnecessary.

**Comment by sggts04** [comment]
If you really can't understand the squashing part, what you can do is delete your fork and PR and create a new fork, clone that, add your code  , and just commit that with a single commit. Just save the code you are adding somewhere else, so you can copy paste it in the new fork and commit it whole in a single commit,

**Comment by Capt-Titanium** [comment]
Should I submit the whole code in a new branch?  This way there'll be only one commit I suppose

**Pull request closed without merging**
