### PR TITLE
Added a preloader gif to the Leaderboard table when it is fetching participants

### PR DESCRIPTION
**Pull request by kumaraditya2002**
https://kumaraditya2002.github.io/Geektoberfest-Main/

### CODE REVIEW

**Comment by sggts04** [comment]
Can you use a better, more simple gif?

**Comment by kumaraditya2002** [comment]
okk

**Comment by sggts04** [comment]
Again, choose something small and simple. No such gifs. Look at the preloader in the profile page.

This gif looks very out of place and also looks pixelated.

**Comment by sggts04** [comment]
Looks good, squash your commits and I will merge.

**Pull request closed without merging**
