### PR TITLE
Add smooth scroll on nav-link click #23

### PR DESCRIPTION
**Pull request by CadencePrestissimo**
1. Added smooth-scroll in main.js
2. Connected it to index.html
3. Added some other required comments

### CODE REVIEW

**Comment by tsukii21** [comment]
Okay, can you provide a live preview from your forked repo?

**Comment by tsukii21** [comment]
Also, there are conflicts. You have changed quite a bit. Merging your PR can break the site. Can you pull the latest changes and work out a way which doesn't change index.html or the CSS such that there are no conflicts.

**Comment by CadencePrestissimo** [comment]
Screenshot (41)

**Comment by tsukii21** [comment]
Okay, it seems everything is right. Fine work!

**Pull request merged**
