### PR TITLE
Added "Move To Top" Button

### PR DESCRIPTION
**Pull request by geeks5551**
#76 

https://geeks5551.github.io/Geektoberfest-Main/

### CODE REVIEW

**Comment by geeks5551** [comment]
@sggts04 Pls Review

**Comment by sggts04** [comment]
Can you add it so that it actually visibly scrolls to the top? Maybe by using jquery

**Comment by sggts04** [comment]
Also the button should only visible when I am scrolled down, not when I am already at the top

**Comment by geeks5551** [comment]
> Can you add it so that it actually visibly scrolls to the top? Maybe by using jquery

Srry I didn't get this issue , pls elaborate

**Comment by geeks5551** [comment]
> Also the button should only visible when I am scrolled down, not when I am already at the top

okk will do it

**Comment by sggts04** [comment]
@geeks5551 look at the scroll to top button on this site: [https://codeforces.com/contest/1430/problem/D](https://codeforces.com/contest/1430/problem/D) (it appears on the top left when scrolling down), when you click on it, you can actually see the site scrolling to the top, instead of just snapping into the top of the site.

**Pull request closed without merging**
