### PR TITLE
updated the home section with a relevant background image in Geektoberfest-Main

### LINKED ISSUE #1: Give the Home Section a relevant background image.
After adding the background image, make sure the text "Geektober.." and the button are still visible properly, you may have to change their styling.

### PR DESCRIPTION
**Pull request by alkatrivedi**
Fixes #1 by updating the home section with a relevant background image. The link to live gh-page for the same is:
https://alkatrivedi.github.io/Geektoberfest-Main/

Thank you.

### CODE REVIEW

**Comment by sggts04** [comment]
@alkatrivedi the live link is not reflecting the changes. I think because your changes are in the new branch while live link is for master branch.
Go to the settings and change the GH Pages branch to your new branch instead of master so that the changes are visible in live link.

**Comment by alkatrivedi** [comment]
Check if the changes are visible now or not?

**Comment by sggts04** [comment]
Good work!

**Comment by alkatrivedi** [comment]
Thanks for merging:)

**Pull request merged**
