### PR TITLE
#7 Adding favicon and Geekhaven logo to navbar

### PR DESCRIPTION
**Pull request by aj0311**
Screenshot (26)

### CODE REVIEW

**Comment by sggts04** [comment]
Could you maybe use a black logo with transparent background? That would look waay better design wise

**Comment by aj0311** [comment]
@sggts can you please share the logo with transparent background. I got black logo but it had white background.

**Comment by sggts04** [comment]
Although can convert any image to transparent using sites like [remove.bg](https://www.remove.bg/) but I found this so you can just use this: [https://github.com/GeekHaven/GeekHaven-2020/blob/master/images/gh.svg](https://github.com/GeekHaven/GeekHaven-2020/blob/master/images/gh.svg)

**Comment by aj0311** [comment]
Screenshot (27)
@sggts04 Is it fine now?

**Comment by sggts04** [comment]
Favicon needs to be replaced too..

**Comment by aj0311** [comment]
Ohk

**Comment by sggts04** [comment]
@aj0311 there have been changes in the repo since you last forked, please resolve the conflicts

**Comment by sggts04** [comment]
@aj0311 You haven't resolved the conflict properly. The structure for nav bar had changed, now you added two navbars, one old and one new.

**Comment by sggts04** [comment]
If you can fix this by today then fine else I'm gonna have to reassign this task

**Comment by Codedude1** [comment]
Hey @sggts04, I would like to work on this.

**Comment by sggts04** [comment]
okay I am reassigning the linked issue, its been 2 days. @Codedude1 make sure to go over the changes and problems in this PR so that you don't make the same errors.

**Comment by sggts04** [comment]
@Codedude1 can you comment on the actual issue instead of pr, so I can assign you there

**Comment by aj0311** [comment]
@sggts04 I thought I had time till today 11.59pm (as you said fix the issue by today) . At least you should have asked me about my progress. I was facing a few difficulties with git and I was about to ask you if I could send a new pr solving the issue. But...

**Comment by sggts04** [comment]
Its ok there will be tons more issues, the event has only just begun. 
I'm sorry I do realize I should have waited a bit more. :)

**Pull request closed without merging**
