### PR TITLE
Navbar redesign 2

### PR DESCRIPTION
**Pull request by s-282**

### CODE REVIEW

**Comment by s-282** [comment]
I have made the Final changes.

**Comment by s-282** [comment]
I have made the final changes.

**Comment by s-282** [comment]
I have made the underlines a bit thinner on navbar.

**Comment by tsukii21** [comment]
mention a live link, here. Remember the link and icon sizes should be same as before

**Comment by s-282** [comment]
https://s-282.github.io/

**Comment by tsukii21** [comment]
Cool! Last thing- drop the opacity of the underlines a bit (0.5 or 0.6 maybe) and squash your commits to a single latest one. (don't sync in between, this may cause problems with the squash, in fact you don't need to sync changes with the main repo as you have only changed the navbar)

**Comment by s-282** [comment]
I have squashed the remaining commits.

**Pull request merged**
