### PR TITLE
make the site responsive for mobile devices

### LINKED ISSUE #172: make this site responsive
All the major work is done, but the site is still unbearable in smartphones. Making this extended site responsive without breaking the existing functionality can prove to be a challenge, but we need help and any contribution is welcome.

### PR DESCRIPTION
**Pull request by shahidsiddiqui786**
fixes #172 

https://livegectoberfestmain.netlify.app/
live link for site

### CODE REVIEW

**Comment by sggts04** [comment]
It has broken the site on how it looks normally.

This heading has become too big.
image

This question mark has been misplaced.
image

When adding responsiveness, original site should remain unchanged.

Moving on to the responsive parts:

The background image shouldn't get stretched like this. ALWAYS maintain aspect ratios of images, it is okay if the full image is not visible, and I think thats the way it was before, which was fine.
image

Next, the hamburger and dark mode toggle should come at extreme right not at left or middle.
image

**Comment by shahidsiddiqui786** [comment]
> It has broken the site on how it looks normally.
> 
> This heading has become too big.
> image
> 
> This question mark has been misplaced.
> image
> 
> When adding responsiveness, original site should remain unchanged.
> 
> Moving on to the responsive parts:
> 
> The background image shouldn't get stretched like this. ALWAYS maintain aspect ratios of images, it is okay if the full image is not visible, and I think thats the way it was before, which was fine.
> image
> 
> Next, the hamburger and dark mode toggle should come at extreme right not at left or middle.
> image

OK,  I will do the required .

**Comment by shahidsiddiqui786** [comment]
@sggts04 
In mobile devices:
In the about section content and symbol should come side by side?
like this
Screen Shot 2020-10-18 at 09 47 09

or may come up aand down ?
like this
Screen Shot 2020-10-18 at 09 52 43

**Comment by sggts04** [comment]
By side

**Comment by shahidsiddiqui786** [comment]
@sggts04 
finally ,Done the  job
please review it

**Comment by sggts04** [comment]
One last thing, looks fine on mobile devices, but when reducing width of browser, the title doesn't scale down at all, and goes out of view.
image

**Comment by shahidsiddiqui786** [comment]
@sggts04 
done it too,
review!

**Comment by sggts04** [comment]
Okay its looks fine now. There is still one last thing tho :P , squash your commits, 7 commits are too much too merge for this issue.

**Comment by shahidsiddiqui786** [comment]
@sggts04 
squashed all commit into one
but getting conflict
what should do now as resolve conflict btn is disable

**Comment by shahidsiddiqui786** [comment]
> 
> 
> @sggts04
> squashed all commit into one
> but getting conflict
> what should do now as resolve conflict btn is disable

oh i resolved the conflict

**Pull request merged**
