### PR TITLE
Added changes

### PR DESCRIPTION
**Pull request by BLACK-PEARLL**
https://black-pearll.github.io/Geektoberfest-Main/

### CODE REVIEW

**Comment by tsukii21** [comment]
make the corners a bit rounded (like the project divs are) and place the participants container in the center (currently its more towards the left). Also, the github and fb links on hover turn dark and are difficult to see, change this to a different color and make sure the dark sqaure border doesn't show up

**Comment by BLACK-PEARLL** [comment]
okk @tsukii21

**Comment by BLACK-PEARLL** [comment]
Untitled

**Comment by BLACK-PEARLL** [comment]
is this fine now?

**Comment by tsukii21** [comment]
yeah great, but its still not at the center

**Comment by sggts04** [comment]
image
these texts should be centered

**Comment by BLACK-PEARLL** [comment]
image

**Comment by BLACK-PEARLL** [comment]
now??

**Comment by BLACK-PEARLL** [comment]
@sggts04  ,i will do that also :)

**Comment by BLACK-PEARLL** [comment]
Untitled
@sggts04  is this okk?

**Comment by BLACK-PEARLL** [comment]
may i now make another pull request?

**Comment by BLACK-PEARLL** [comment]
may i now commit all these changes?

**Comment by tsukii21** [comment]
Okay, its looking great now. Yeah commit the changes

**Comment by BLACK-PEARLL** [comment]
okk

**Comment by BLACK-PEARLL** [comment]
commit done :)

**Pull request merged**
