### PR TITLE
created profile page

### PR DESCRIPTION
**Pull request by kumarmanish03**
#125

### CODE REVIEW

**Comment by sggts04** [comment]
Some things.

1. This file should be outside, not in public folder.

2. You need to get the username from the URL as a parameter. So that we can just link a URL to someone and it would have their details, instead of them having to open the page and then type in their username. I mentioned the example URL in the issue, getting the parameter from URL is really easily btw, just google.
Keep the form too, thats good, but make the form when submitted, redirect you to the URL with the username as parameter, and then JS will check the parameter and show details.

3. Share a livelink next time you make these changes.

**Comment by tsukii21** [comment]
@sggts04 changing the top level file structure can disable the participants section, so remind me when merging this

**Comment by kumarmanish03** [comment]
@sggts04 The Above I got it, One more thing, Is I have to extract the data from JSON file ex. extract the name, image, etc. OR I should simply display raw JSON data as I did earlier

**Comment by sggts04** [comment]
you have extract the name, image, about, social links, and the list of PRs. and display them, imagine it as a profile page of someone participating. BUT, right now you don't need to do any styling, just display these elements after extracting.
The styling and design part will be done by someone else in another issue.

**Comment by sggts04** [comment]
can you share a live link? (If this is your final commit)

**Comment by kumarmanish03** [comment]
https://pensive-albattani-93f1c7.netlify.app/?username=kumarmanish03
accordingly you can check for other usernames

**Pull request merged**
