### PR TITLE
added a search bar to search user

### LINKED ISSUE #282: In the profile page, add a search functionality to search for another user.
In the profile page, below the profile of whoever's profile is requested, add a new search section with a search bar which accepts a username and redirects to the profile page of the username requested.

Give the section a proper heading and proper styling, make sure the styling matches the styling of the profile page.

### PR DESCRIPTION
**Pull request by shahidsiddiqui786**
fixes #282 

here is  the live link
https://livegectoberfestmain.netlify.app/profile.html?username=Priyansh-09

### CODE REVIEW

**Comment by sggts04** [comment]
Firstly, not responsive at all, appears broken right now
image

Secondly, badly placed. It should either be above someone else's profile, or below their profile. Not in between their profile.

**Comment by shahidsiddiqui786** [comment]
@sggts04 
is it ok to place it above , like this
Screenshot_2020-10-24 Profile-Shahid(3)

**Comment by sggts04** [comment]
Yes, above is fine, but it needs to be in the center, not at the right.

**Comment by shahidsiddiqui786** [comment]
@sggts04 
check now live site
https://livegectoberfestmain.netlify.app/profile.html?username=Priyansh-09
is everything fine?

**Comment by sggts04** [comment]
image

It isn't aligned at all, vertical alignment should also be proper.
Also, by default make it a little lengthier, its too small.

**Comment by shahidsiddiqui786** [comment]
@sggts04 
done

**Comment by sggts04** [comment]
cool, but there's no need to make the search bar sooo big, just a little bigger than the default one is just fine, no one has a huge username.

**Comment by shahidsiddiqui786** [comment]
> 
> 
> cool, but there's no need to make the search bar sooo big, just a little bigger than the default one is just fine, no one has a huge username.

ok,done

**Comment by shahidsiddiqui786** [comment]
> 
> 
> > cool, but there's no need to make the search bar sooo big, just a little bigger than the default one is just fine, no one has a huge username.
> 
> ok,done

wait

**Comment by shahidsiddiqui786** [comment]
@sggts04 
finally. done

**Pull request merged**
